---
title: 'Functional-Light JavaScript'
Subtitle: > 
    This book is a balanced, pragmatic look at FP in JavaScript. 
    The first edition is now complete. Read here online for free
subject: Functional JavaScript
author:
- Kyle Simpson
keywords: js, fljs, functional js, functional programming
rights: Creative Commons Non-Commercial Share Alike 3.0
language: en-US
lang: en
cover-image: gitbook/images/marketing/front-cover-hd.png
tags: [pandoc, pdf, epub, mobi creation]
format-arguments:
    pdf: >
        -S
        --toc
        --number-sections
        -V mainfont='Latin Modern Roman' 
        -V sansfont='Times New Roman' 
        -V monofont=Arial -V fontsize=12pt -V version=1.10
    html: -S --toc-depth=2 --chapters --number-sections --toc
    epub: -S --epub-embed-font=OpenSans-Regular.ttf --epub-chapter-level=2 --toc-depth=2 --number-sections --toc
    mobi: ok
...
