---
title: 'Functional-Light JavaScript'
Subtitle: > 
    This book is a balanced, pragmatic look at FP in JavaScript. 
    The first edition is now complete. Read here online for free
subject: Functional JavaScript
author:
- Kyle Simpson
keywords: js, fljs, functional js, functional programming
rights: Creative Commons Non-Commercial Share Alike 3.0
language: en-US
lang: en
cover-image: cover.jpg
tags: [pandoc, pdf, epub, mobi creation]
...